name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: check loc
        run: ls

      - name: decode jarsigner key
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: /tmp/keystore
          isAbsolutePath: false
          file: key.txt
          content: ${{ secrets.KEY_JKS_BASE_64 }}

      - name: decode keystore
        run: base64 --decode -i tmp/keystore/key.txt -o tmp/keystore/key.jks

      - name: check loc
        run: ls

      - name: build
        run: mvn verify -DskipTests -P jenkins

      - name: Set version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | cut -c 2-)" >> $GITHUB_ENV

      - name: Set prefix
        run: echo "PREFIX=$(echo $"pgCodeKeeper-")" >> $GITHUB_ENV

      - name: set linux build name
        run: echo "LINUX_BUILD=${{ env.PREFIX}}${{ env.RELEASE_VERSION }}-linux.gtk.x86_64.tar.gz" >> $GITHUB_ENV

      - name: set windows build name
        run: echo "WINDOWS_BUILD=${{ env.PREFIX }}${{ env.RELEASE_VERSION }}-win32.win32.x86_64.zip" >> $GITHUB_ENV

      - name: set cli build name
        run: echo "CLI_BUILD=pgCodeKeeper-cli-${{ env.RELEASE_VERSION }}.zip" >> $GITHUB_ENV

      - name: set updatesite name
        run: echo "UPDATESITE=pgCodeKeeper-updatesite-${{ env.RELEASE_VERSION }}.zip" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к GitHub API
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: pgCodeKeeper ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: check loc
        run: ls ru.taximaxim.codekeeper.mainapp/product/rcp/target/products

      - name: Upload Release linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/product/rcp/target/products/${{ env.LINUX_BUILD }}
          asset_name: ${{ env.LINUX_BUILD }}
          asset_content_type: application/zip

      - name: Upload Release windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/product/rcp/target/products/${{ env.WINDOWS_BUILD }}
          asset_name: ${{ env.WINDOWS_BUILD }}
          asset_content_type: application/zip

      - name: Upload Release cli build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/product/standalone/target/products/${{ env.CLI_BUILD }}
          asset_name: ${{ env.CLI_BUILD }}
          asset_content_type: application/zip

      - name: Upload Release updatesite
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/products/${{ env.UPDATESITE }}
          asset_name: ${{ env.UPDATESITE }}
          asset_content_type: application/zip
