name: Test push to other repo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: baslo2/tycho-example
          token:  ${{ secrets.API_TOKEN_GITHUB }}
          path: ru.taximaxim.codekeeper.mainapp/deploy/tycho-example/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: check loc
        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/

      - name: check loc
        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/tycho-example/

      - name: build
        run: mvn clean deploy -DskipTests

      - name: check loc
        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/

      - name: check loc
        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/repository/

      - name: copy updatesite
        run: cp -R ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/repository/ ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/tycho-example/update/

      - name: check loc
        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/tycho-example/update

#      - name: add new dir
#        run: mkdir -p ${{ github.workspace }}/test/update/
#
#      - name: check loc
#        run: ls ${{ github.workspace }}/test

#      - name: setup git config
#        run: |
#          git config user.name "GitHub Actions Bot"
#          git config user.email "<>"

#      - name: check git command
#        run: |
#         cd ${{ github.workspace }}/test
#         git remote show origin
#
#      - name: check git command
#        run: |
#          cd ${{ github.workspace }}/test
#          git status
#
#      - name: copy files
#        run: cp ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/repository/p2.index ${{ github.workspace }}/test/update/repository/p2.index
#
#      - name: check loc
#        run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/

#      - name: check loc
#        run: ls ${{ github.workspace }}/test/
#
#      - name: check loc
#        run: ls ${{ github.workspace }}/test/updatesite/repository
#
#      - name: check git command
#        run: |
#          cd ${{ github.workspace }}/test
#          git status
          
#      - name: new branch
#        run: |
#          cd ${{ github.workspace }}/test
#          git branch test
#
#      - name: checkout
#        run: |
#          cd ${{ github.workspace }}/test
#          git checkout test

      - name: Set prefix
        run: echo "PREFIX=$(echo $"10.0.0")" >> $GITHUB_ENV

      - name: git commands
        run: |
          cd ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/deploy/tycho-example/
          git add update
          git commit -m "some ${{ env.PREFIX }} test message"
          git push origin HEAD
#
#      - name: commit
#        run: |
#          cd ${{ github.workspace }}/test
#          git commit -m test
#
#      - name: check git command
#        run: |
#          cd ${{ github.workspace }}/test
#          git status
#
#      - name: check git command
#        run: |
#          cd ${{ github.workspace }}/test
#          git remote show origin
#
#      - name: git push
#        run: |
#          cd ${{ github.workspace }}/test
#          git push origin HEAD