name: Test push to other repo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>

      - name: build
        run: mvn clean deploy -DskipTests -P deploy-github -X

      # - name: Checkout tools repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: baslo2/hero
      #     token:  ${{ secrets.API_TOKEN_GITHUB }}
      #     path: test

      # - name: check loc
      #   run: ls ${{ github.workspace }}/test

      # - name: add new dir
      #   run: mkdir -p ${{ github.workspace }}/test/updatesite

      # - name: check loc
      #   run: ls ${{ github.workspace }}/test

      # - name: setup git config
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"

      # - name: check git command
      #   run: |
      #    cd ${{ github.workspace }}/test
      #    git remote show origin

      # - name: check git command
      #   run: |
      #    cd ${{ github.workspace }}/test
      #    git status

      # - name: copy files
      #   run: cp ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/repository ${{ github.workspace }}/test/repository

      # - name: check loc
      #   run: ls ${{ github.workspace }}/ru.taximaxim.codekeeper.mainapp/updatesite/target/

      # - name: check loc
      #   run: ls ${{ github.workspace }}/test/
